### ISSUE TITLE
Cannot upgrade react-scripts to 3.1.2 due to webpack dependency

### ISSUE THREAD

**Issue by Vovan-VE** [DocSpring/craco-less#24]
Upgrade `react-scripts` to `3.1.2` cause the following tree:

```
├─┬ craco-antd@1.12.0
│ └─┬ craco-less@1.12.0
│   └── webpack@4.39.1 
└─┬ react-scripts@3.1.2
  └── webpack@4.40.2 
```

As the result, the `./node_modules/webpack` is 4.39.1. This cause `react-scripts` to report an error ("prefligh check").

**Comment by alexandrtovmach** [comment]
@Vovan-VE  Thanks for the issue. Let me check

**Comment by alexandrtovmach** [comment]
@ndbroadbent Hello, I've faced with your problems of webpack version conflicts, and yes I've read all issues (#3 #4 ) about it and checked your _update_deps.js_ solution. Looks great, but I have one idea ― why we can't just remove `webpack` from dependencies?

I already did that locally, run tests and everything works fine, because `webpack` hoisting from `react-scripts`. What you think about that? From my point of view *craco-less* using only in apps were already installed `webpack` or `react-scripts/webpack`, so we don't need to install it from own side, and can just inherit it.

**Comment by alexandrtovmach** [comment]
@ndbroadbent Could you please check #25

**Comment by alexandrtovmach** [comment]
@Vovan-VE Fix already available in [1.13.0](https://www.npmjs.com/package/craco-less/v/1.13.0). Please upgrade your dependency:
```sh
yarn upgrade craco-less@1.13.0

# or

npm install craco-less@1.13.0
```

**Comment by Vovan-VE** [comment]
I did not install `craco-less` directly. I use `craco-antd`, which is latest `1.12.0`. It depends on `craco-less: ^1.12.0`. So, `craco-antd` also should be updated.

**Comment by ndbroadbent** [comment]
Hi @Vovan-VE, sorry about that! I'm running into some problems with the `craco-antd` upgrade for the latest version of craco, but I've [posted an issue](https://github.com/gsoft-inc/craco/issues/115), and hopefully will be able to figure this out soon.

**Comment by Vovan-VE** [comment]
`react-scripts`, what are you doing? It's `3.2.0` now. The `webpack` dependency is now `4.41.0`. Probably, upgrade would be even more difficult.

**Comment by ndbroadbent** [comment]
Hi @Vovan-VE, yes I'm struggling to upgrade `craco-antd` to work with the latest `react-scripts` and `craco` versions. Here's some more information about an issue that I can't figure out: https://github.com/gsoft-inc/craco/issues/115#issuecomment-538449902

The tests are now broken and I can't figure out how to get the babel import plugin to work again. Any help would be really appreciated, otherwise unfortunately I don't have any more time to look into this issue. (And I'm not currently using any of these libraries.)

**Comment by alexandrtovmach** [comment]
@ndbroadbent Please take a look https://github.com/DocSpring/craco-antd/pull/22

I've updated tests, and it seems to be stable

**Comment by ndbroadbent** [comment]
Thanks @alexandrtovmach, but unfortunately that doesn't fix the issue. I haven't been able to figure out how to get the babel import rule to work again. Maybe we can skip the `overrideCracoConfig ` function, and just do everything inside `overrideWebpackConfig`.

**Comment by Vovan-VE** [comment]
Your plugins v1.12.0 works fine with craco 5.5.0. I suppose, the problem is rising from react-scripts itself. But it still can be some unexpected behavior of craco due to react-scripts upgrade - I did not research it.

**Comment by ndbroadbent** [comment]
Hi everyone, I've released new versions of `craco-less` and `craco-antd`:

- `craco-less` version `1.14.4`
- `craco-antd` version `1.14.1`

These both depend on the latest versions of `craco` (`^5.5.0`) and `react-scripts` (`^3.2.0`). (`craco-less` also has a matching `webpack` dependency for version `4.41.0`, which matches `react-scripts`. This is needed to silence some warnings when installing dependencies.)

Please try out these latest versions and let me know if you are still running into any issues. Thanks!
