### ISSUE TITLE
Support for react-scripts 3.3.0 (webpack 4.41.2)

### ISSUE THREAD

**Issue by Vovan-VE** [DocSpring/craco-less#27]
Hello!

`react-scripts` released `3.3.0` version. It now depends on `webpack: 4.41.2`. Please, update your dependencies to be able to update `react-scripts`.

**Comment by ndbroadbent** [comment]
Hello, thanks for letting me know! I should really set up [Dependabot](https://dependabot.com/) so that it can help to update the versions automatically. Unfortunately I'm a bit busy at the moment, so it would be a big help if you could please send a PR to update the versions? I can merge it in and release a new version. And then I'll try to get Dependabot set up soon so that it can do this automatically. Thanks!
