### ISSUE TITLE
why can't I use style loader in production env?

### ISSUE THREAD

**Issue by zhang6464** [DocSpring/craco-less#32]
```
    if ( 
      (context.env === "development" || context.env === "test") &&
      rule.loader.includes(`${pathSep}style-loader${pathSep}`)
    ) {
      lessRule.use.push({
        loader: rule.loader,
        options: {
          ...rule.options,
          ...(pluginOptions.styleLoaderOptions || {})
        }
      });
```
if `context.env` equals `production`, and i have a style loader in list, then an error occurs, it's not expected

**Comment by tux-tn** [comment]
It's because react-scripts itself is only using ```style-loader```in dev for hot module reloading. In production it relay on ```MiniExtractCssPlugin```to extract css and generate a style file.
You can find [here react-script's webpack config](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L82)
